export const Political = {
    '基隆市': 'Keelung City',
    '台北市': 'Taipei City',
    '新北市': 'New Taipei City',
    '桃園市': 'Taoyuan City',
    '新市縣': 'Hsinchu County',
    '新竹市': 'Hsinchu City',
    '苗栗縣': 'Miaoli County',
    '台中市': 'Taichung City',
    '彰化縣': 'Changhua County',
    '南投縣': 'Nantou County',
    '雲林縣': 'Yunlin County',
    '嘉義縣': 'Chiayi County',
    '嘉義市': 'Chiayi City',
    '台南市': 'Tainan City',
    '高雄市': 'Kaohsiung City',
    '屏東縣': 'Pingtung County',
    '宜蘭縣': 'Yilan County',
    '花蓮縣': 'Hualien County',
    '台東縣': 'Taitung County',
    '澎湖縣': 'Penghu County',
    '金門縣': 'Kinmen County',
    '連江縣': 'Lienchiang County'
}